### ISSUE TITLE
Redundant empty else-clause.

### ISSUE THREAD

**Issue by martinb3** [rackspace-cookbooks/pythonstack#132]
pythonstack$ rubocop  
Inspecting 56 files
.......C................................................

Offenses:

recipes/application_python.rb:142:16: C: Redundant empty else-clause.
               else
               ^^^^
recipes/application_python.rb:156:13: C: Redundant empty else-clause.
            else
            ^^^^

56 files inspected, 2 offenses detected

**Comment by prometheanfire** [comment]
fixed a month ago
